### PR TITLE
Implement fix for SFTP seclib constants.

### PR DESCRIPTION
**Pull request by bangerkuwranger**
Allows magento v2.1.x with updated phpseclib to properly upload feed files via sftp without throwing an 'undefined constant' exception. This is a targeted PR including only the SFTP fix from [PR 6](https://github.com/bazaarvoice/magento2-extension/pull/6).

### CODE REVIEW

**Comment by chrismshea** [comment]
@nntoan We attempted to implement the changes as you suggested, but it was not working.  Do you have this working on a 2.1 install?  If so could you submit submit a PR with the complete working change?

**Comment by nntoan** [comment]
@chrismshea How did you add the plugin?

**Comment by drake1701** [comment]
@nntoan I was unable to get the plugin method to fire on the Sftp class, or the preference method for that matter, unless I changed the injected class in the Feed class to our copy, as seen in this PR.

**Comment by chrismshea** [comment]
@nntoan Any thoughts before I implement the original version of this PR?

**Pull request closed without merging**
